### ISSUE TITLE
prompt info in the command line after "setup"

### ISSUE THREAD

**Issue by Grienauer** [drubb/drupal-gitpod#1]
If a user opens the project in gitpod, it would be great if we could have some info in the commandline.
starting up takes some time, and new users are maybe not aware, that they have to wait a bit.
A solution would be to add some text to the commandline:
"First time setup takes a while. we will inform you when the system is ready with a popup" <- ton't know how to name the info which pops up :)
Also it would be great, to ad a ```drush uli```after the system is started, so a user can just click on it and is already logged in too, also it would indicate, that everything is ready.

thx!

**Comment by drubb** [comment]
I have to think about it, but this should be possible using a lock file:

The setup script ("Run & Start" terminal) creates a lock file and deletes it when the server is being started. The second terminal ("Command Line") displays a message, waits for the lock file to be removed, shows a message announcing the popup window and does drush uli.

**Comment by drubb** [comment]
No need for a lock file, Gitpod has a builtin command to wait for instance launches.

I've updated the code incorporating your suggestions:

* better explanation of startup process
* notify user about the finished build
* provide a Drush login link

Also, README is now kind of context-aware and displays instructions related to the chosen environment.

Thanks for your suggestions, closing this issue for now.
